name: Fly Deploy

on:
  push:
    branches:
      - main
      - fixing-dockerfile

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: flyctl setup
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploying ...
        run: flyctl deploy --remote-only
